---
title: "Data Import"
output: github_document
---

```{r, echo = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## Data Import: CSVs

Let's import data using the `readr` package.

```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

Look at the data

```{r}
litters_df

head(litters_df)
tail(litters_df)
```

```{r, eval = FALSE}
view(litters_df)
```

```{r}
skimr::skim(litters_df)
```



`read_csv` options..

```{r, eval = FALSE}
read_csv("data/FAS_litters.csv", na = c("","NA",999,88, skip=2)
```


## Other File Formats

We need to read in an excel spreadsheet ...

```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```

```{r, eval = FALSE}
view(mlb_df)
```

```{r}
lotr_words_df = read_excel("data/LotR_words.xlsx", range="B3:D6")
```

## Still more formats ...

Read in a SAS dataset.

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
view(pulse_df)
```

## Data Export

```{r}
write_csv(lotr_words_df, file = "data/LotR_words_df.csv")
```


## Why not base r???
 better to use _ instead of .
 
```{r}
dont_do_this_df = read.csv("data/FAS_litters.csv")
```

